import { DialogueLine, FadeTransitionType } from "./types";

const script : DialogueLine[] = [
    {
        id: "fin", // Unique ID for this line
        name: "",
        text: "*Les Nodites sont ko au sol, Va est debout triomphant. Syel le rejoint en descendant par l'escalier de secours.*",
        background: 'noir',
        backgroundTransition: {
          easing: FadeTransitionType.easeIn,
          duration: 3000,
        },
    },
    {
      id: "fin1",
      name: "Syel",
      text: "Tu leur a pas fait de cadeau dis donc... Ils ont l'air complètement sonnés.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "detendu",
        right: "syel",
        rightMood: "etonne",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin2",
      name: "Vangva",
      text: "Je n'ai fait que me défendre ! Après tout, ils étaient armés de couteaux.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "hausse_epaules",
        right: "syel",
        rightMood: "sourit",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin3",
      name: "Syel",
      text: "Haha... Je ne peux pas croire une seconde que tu te sois senti menacé.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "rigole",
        right: "syel",
        rightMood: "sourit",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin3.1",
      text: "...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense",
        right: "syel",
        rightMood: "attend",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin4",
      name: "Vangva",
      text: "Au fait... Quelque chose ne va pas ? J'ai ressenti beaucoup de colère... quand tu m'as prêté ton énergie.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "embete",
        right: "syel",
        rightMood: "etonne",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin5",
      name: "Syel",
      text: "...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin6",
      name: "Syel",
      text: "Ce n'est rien...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin7",
      name: "Vangva",
      text: "Mmh...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "embete",
        right: "syel",
        rightMood: "attend",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin8",
      text: "...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "embete",
        right: "syel",
        rightMood: "attend",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin9",
      name: "Syel",
      text: "C'est juste que... Écoute, je comprends pourquoi on fait tout ça... pourquoi on arrête ces personnes. Ça ne me plait juste pas trop d'utiliser ce genre de stratagème pour les piéger. Et puis...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin11",
      text: "*le téléphone sonne brusquement*",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "choque",
        right: "syel",
        rightMood: "etonne",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin12",
      name: "Vangva",
      text: "C'est Ilyem ! Excuse-moi...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense_tel",
        right: "syel",
        rightMood: "bras_frustre",
        leftFlip: true,
        rightFlip: true,
      },
    },
    {
      id: "fin13",
      name: "Vangva",
      text: "Ily ! Tout va bien de ton côté ?!",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ouvert",
        right: "syel",
        rightMood: "attend",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin14",
      name: "Ilyem",
      text: "Oui, oui, pas de problème pour moi. Ils m'ont laissée partir sans insister.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ouvert",
        right: "syel",
        rightMood: "attend",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin15",
      name: "Vangva",
      text: "Je suis soulagé. C'est grâce à toi qu'on a pu arrêter autant de monde, mais... De nous tous, c'est toi qui étais la plus exposée. Y aller seule était vraiment risqué, tu sais...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ferme",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin16",
      name: "Ilyem",
      text: "Allons bon ? C'est toi qui t'inquiètes pour moi maintenant ? C'est le monde à l'envers !",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_fermé",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin17",
      name: "Vangva",
      text: "Ily, je suis sérieux... Je sais quels sont les enjeux pour toi... Mais tu ferais mieux de ne plus prendre autant de risque à l'avenir. Tu as eu les informations que tu recherchais au moins ?",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ouvert",
        right: "syel",
        rightMood: "attend",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin18",
      name: "Ilyem",
      text: "... Non. Ils ne savent rien... Ce ne sont pas les Nodistes qui ont ma sœur, Vangva, ou alors ils mentent vraiment très bien sous la menace.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ouvert",
        right: "syel",
        rightMood: "bras_frustre",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin19",
      name: "Vangva",
      text: "Ah... Je suis désolé.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ouvert",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: false,
        rightFlip: true,
      },
    },
    {
      id: "fin20",
      name: "Ilyem",
      text: "On finira bien par retrouver sa trace, hein ? Il faut juste que je parvienne à rester patiente...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ferme",
        right: "syel",
        rightMood: "bras_frustre",
        leftFlip: false,
        rightFlip: true,
      },
    },
   {
      id: "fin21",
      name: "Vangva",
      text: "Oui. On y arrivera, j'en suis convaincu. Je te laisse, on en reparle ce soir.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "au_tel_ouvert",
        right: "syel",
        rightMood: "attend",
        leftFlip: false,
        rightFlip: true,
      },
    },
   {
      id: "fin22",
      name: "Vangva",
      text: "Désolé, je t'ai coupé.",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: true,
        rightFlip: true,
      },
    },
   {
      id: "fin23",
      name: "Syel",
      text: "Ne t'en fais pas. En gros, ce que je veux dire, c'est que...",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "pense",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: true,
        rightFlip: true,
      },
    },
   {
      id: "fin23",
      name: "*voix hors champ",
      text: "Putain... Il m'a pas loupé ce con !",
      background: 'impasse',
      charactersOnScreen: {
        left: "vava",
        leftMood: "choque",
        right: "syel",
        rightMood: "etonne",
        leftFlip: false,
        rightFlip: true,
      },
    },
   {
      id: "fin24",
      name: "Ira",
      text: "C'est la dernière fois que je joue les appâts ! Je savais bien que ce serait un plan foireux...",
      background: 'impasse',
      charactersOnScreen: {
        left: "ira",
        leftMood: "rale",
        middle: "vava",
        middleMood: "regard_froid",
        right: "syel",
        rightMood: "bras_fuyant",
        leftFlip: false,
        middleFlip: false,
        rightFlip: true,
      },
    },
];

export default script;